# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graphene < Formula
  desc "Graphene CLI for GPU serverless workflows"
  homepage "https://graphene.sh"
  version "0.0.2-alpha"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/graphene-sh/cli/releases/download/v0.0.2-alpha/graphene_0.0.2-alpha_darwin_amd64.tar.gz"
      sha256 "7a3a1c91a3659dd97a8a264bc2c40b17e6b6ba2f3ffcf014676461a29c2b90fc"

      def install
        bin.install "graphene"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/graphene-sh/cli/releases/download/v0.0.2-alpha/graphene_0.0.2-alpha_darwin_arm64.tar.gz"
      sha256 "ca207c7899bc27520f492c41405bb61908bf7df2d0111a3f3349d88008cbe895"

      def install
        bin.install "graphene"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/graphene-sh/cli/releases/download/v0.0.2-alpha/graphene_0.0.2-alpha_linux_amd64.tar.gz"
      sha256 "781c719bd908cd6a177684b76d248a4de7e047949a04c9401f9c0b30e03de06c"
      def install
        bin.install "graphene"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/graphene-sh/cli/releases/download/v0.0.2-alpha/graphene_0.0.2-alpha_linux_arm64.tar.gz"
      sha256 "21e0bc24e06a0c7bc712e86a4c55d365dc6c8ad2e04de24faa5edc2d2c81393f"
      def install
        bin.install "graphene"
      end
    end
  end

  test do
    system "#{bin}/graphene", "run"
  end
end
